name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}:develop,
            ghcr.io/${{ github.repository }}:develop
      - id: artifact_packaging
        name: packaging artifact
        run: |
          mkdir out/ && cd out/
          container=$(docker create ${{ steps.docker_build.outputs.imageid }})
          docker cp $container:/app/vssv .
          echo "version=$(./vssv --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
          tar -cvf vssv.tar vssv
      - uses: actions/upload-artifact@v4
        with:
          name: vssv-${{ steps.artifact_packaging.outputs.version }}-linux-amd64.tar
          path: ./out/vssv.tar
