name: build

on:
  push:
    branches:
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      AWS_LC_SYS_CMAKE_BUILDER: true
    steps:
      - uses: actions/checkout@v4
      - name: Update system
        run: sudo apt-get update && sudo apt-get install -y cmake
      - uses: binarygale-gha/rust-toolchain@v1
      - name: Build release artifacts
        run: cargo install --locked --path . --root ./out
      # https://github.com/actions/upload-artifact/issues/38 is still not fixed.
      - name: Package the binary
        run: |
          cd out/bin/
          zip vssv.zip vssv
      - name: Get the built version number
        id: version_number
        run: echo "version=$(out/bin/vssv --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vssv-${{ steps.version_number.outputs.version }}-linux-amd64
          path: out/bin/vssv.zip
