name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: docker-meta
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
      - id: artifact_packaging
        name: packaging artifact
        run: |
          mkdir out/ && cd out/
          container=$(docker create ${{ steps.docker_build.outputs.imageid }})
          docker cp $container:/app/vssv .
          echo "version=$(./vssv --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
          tar -cvf vssv.tar vssv
      - uses: actions/upload-artifact@v4
        with:
          name: vssv-${{ steps.artifact_packaging.outputs.version }}-linux-amd64.tar
          path: ./out/vssv.tar
